networks:
  db:
services:
  api:
    container_name: auth-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL:?set in .env}
      - API_PORT=${API_PORT:-8000}
      - JWT_SECRET=${JWT_SECRET:?set in .env}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: auth-db
    networks:
      - db
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres} -d ${DATABASE_NAME}"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always